export const TOP_BAR_VISIBILITY_CHANGE = 'topBarVisibilityChange'
export const OVERLAY_SCROLL_BAR_SCROLL = 'overlayScrollBarScroll'
export const BEWLY_MOUNTED = 'bewlyMounted'
export const DRAWER_VIDEO_ENTER_PAGE_FULL = 'drawerVideoEnterPageFull'
export const DRAWER_VIDEO_EXIT_PAGE_FULL = 'drawerVideoExitPageFull'
export const IFRAME_PAGE_SWITCH_BEWLY = 'iframePageSwitchBewly'
export const IFRAME_PAGE_SWITCH_BILI = 'iframePageSwitchBili'
