name: Bug Report
description: 报告问题
title: '[BUG] 请在这里简单描述一下问题'
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## BUG 提出
        Edge 受遥遥领先的 Edge Addons 审核导致版本更新永远落后于 Chrome，且审核问题不是我们控制的，所以后面已经直接取消上架 Edge Addons
        Edge 浏览器也可以通过 [Chrome Web Store 下载](https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp)，不要因为 **Edge 浏览器** 在 [Chrome Web Store](https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp) 上弹出大提示而又下回 Edge 版本
        如果是旧版本的问题或是已经有人提问过的问题将会关闭

  - type: textarea
    attributes:
      label: 环境
      description: 插件版本和浏览器版本
      placeholder: |
        浏览器 (如 Chrome):
        浏览器版本 (如 126.0.6478.126):
        BewlyBewly 版本 (如 0.20.1):
      value: |
        浏览器 (如 Chrome):
        浏览器版本 (如 126.0.6478.126):
        BewlyBewly 版本 (如 0.20.1):
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 如何重现, 最好带有截图或视频以便排查
      placeholder: |
        请预先搜索是否有提到的 issue 否则重复的 issue 会被关闭
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期结果
      description: 预期结果
    validations:
      required: false
