name: 问题报告
description: 遇到错误请在此报告。
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## 问题报告
        报告问题之前请先看“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面。

        标题不填或直接随便写类似“bug”“错误”“有问题”简单带过的 issue 直接 close + lock 不解释，如果是旧版本的问题或是已经有人提问过的问题将会关闭。

        功能请求不是在问题报告里面写的，请[开启空 issue](https://github.com/BewlyBewly/BewlyBewly/issues/new)。

        若遇到页面相关问题（比如某页面下出现了不该出现的元素），我们建议一并附上发生问题的页面链接。

        ### Edge
        Edge 受遥遥领先的 Edge Addons 审核导致版本更新永远落后于 Google Chrome，且审核问题不是我们控制的，所以后面已经直接取消上架 Edge Addons。

        [Edge 浏览器也可以通过 Chrome Web Store 下载](https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp)，**不要因为 Edge 浏览器在 Chrome Web Store 上弹出大提示而又下回 Edge 版本**。

        ### Safari
        不会上架 Safari，DKLM 苹果我注册苹果开发者每年送苹果 99 美元连资格也不给，系统和客服一直说系统说你有一个或多个问题导致无法注册也没解决办法，另外 Apple 傻閪弱智 on9 笨柒豬閪脑回路 Safari 和系统更新绑定，Safari 我屌你老母吔屎啦快撚啲死柒咗佢啦邊撚個會用佢

  - type: textarea
    attributes:
      label: 环境信息
      description: 【请勿修改 issue 模版。】扩展版本、浏览器版本、以及你做出的自定义设置。
      placeholder: |
        - 浏览器（如 Google Chrome）：
        - 浏览器版本（如 126.0.6478.126）：
        - BewlyBewly 版本（如 0.20.1）：

        如果你修改了 BewlyBewly 的设置，请写在下面以方便我們排查問題（可粗略写成类似“设置了××后出现这个问题”〔将“××”替换为你的设置项〕）：

      value: |
        - 浏览器（如 Google Chrome）：
        - 浏览器版本（如 126.0.6478.126）：
        - BewlyBewly 版本（如 0.20.1）：

        如果你修改了 BewlyBewly 的设置，请写在下面以方便我們排查問題（可粗略写成类似“设置了××后出现这个问题”〔将“××”替换为你的设置项〕）：

    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 如何重现，最好带有截图或视频以便排查。
      placeholder: |
        请预先搜索此问题是否在其他 issue 中出现过，重复的 issue 会被 close + lock。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期行为
      description: 你认为应该是什么行为。
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: 最终确认
      description: 请确认以下所有内容，否则将被 close。
      options:
        - label: 我确认在停用 BewlyBewly 并强制刷新（按住 Shift 键的同时按刷新键）后，问题不再出现。
          required: false
        - label: 我确认此问题未在其他 issue 中出现过。
          required: false
        - label: 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
          required: false
        - label: 我确认我正在使用最新的 BewlyBewly 版本。
          required: false

  - type: checkboxes
    attributes:
      label: 作出贡献？
      description: 【此选项非必选，如果你不晓得这里在说什么，请勿勾选。】我们欢迎任何人贡献代码，见 [CONTRIBUTING.md](https://github.com/BewlyBewly/BewlyBewly/blob/main/docs/CONTRIBUTING.md)。
      options:
        - label: 我将自行提交一个 PR 来解决此问题。
          required: false
