name: Bug Report
description: 报告问题
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## BUG 提出
        Edge 受遥遥领先的 Edge Addons 审核导致版本更新永远落后于 Chrome，且审核问题不是我们控制的，所以后面已经直接取消上架 Edge Addons
        Edge 浏览器也可以通过 [Chrome Web Store 下载](https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp)，不要因为 **Edge 浏览器** 在 [Chrome Web Store](https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp) 上弹出大提示而又下回 Edge 版本

        不会上架 Safari，DKLM苹果我注册苹果开发者每年送苹果 99 美元连资格也不给，系统和客服一直说系统说你有一个或多个问题导致无法注册也没解决办法，另外 Apple 傻閪弱智on9笨柒豬閪脑回路 Safari 和系统更新绑定，Safari 我屌你老母吔屎啦快撚啲死柒咗佢啦邊撚個會用佢

        如果是旧版本的问题或是已经有人提问过的问题将会关闭

  - type: textarea
    attributes:
      label: 环境
      description: 插件版本和浏览器版本
      placeholder: |
        浏览器 (如 Chrome):
        浏览器版本 (如 126.0.6478.126):
        BewlyBewly 版本 (如 0.20.1):
      value: |
        浏览器 (如 Chrome):
        浏览器版本 (如 126.0.6478.126):
        BewlyBewly 版本 (如 0.20.1):
    validations:
      required: true

  - type: textarea
    attributes:
      label: 问题描述
      description: 如何重现, 最好带有截图或视频以便排查
      placeholder: |
        请预先搜索是否有提到的 issue 否则重复的 issue 会被关闭
    validations:
      required: true

  - type: textarea
    attributes:
      label: 预期结果
      description: 预期结果
    validations:
      required: false
