name: Build

on:
  push:
    branches:
      # The branch where the project source code resides
      # 项目源代码所在的分支
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build Extension
        run: pnpm build

      - name: Upload Zip
        uses: actions/upload-artifact@v3
        with:
          name: BewlyBewly Zip
          path: extension
