name: Upload extension zip on release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: Build
        run: |
          pnpm build
          pnpm build-firefox

      - name: Build Extension
        run: |
          pnpm pack:zip
          pnpm pack:zip-firefox

      - name: Upload assets to a Release
        uses: meeDamian/github-release@v2.0.3
        with:
          files: |
            extension.zip
            extension-firefox.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          gzip: false
