name: 测试版编译

on:
  workflow_dispatch:
jobs:
  test:
    name: 测试
    strategy:
      matrix:
        node: [lts/*, lts/-1]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: 安装 pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: |
            - args: [--frozen-lockfile]

      - name: 安装依赖
        run: pnpm install

      - name: Chrome 插件编译
        run: pnpm build

      - name: Chrome 打包
        run: pnpm pack:crx && pnpm pack:zip

      - name: Firefox 插件编译
        run: pnpm build-firefox

      - name: Firefox 打包
        run: pnpm pack:xpi

      - name: 上传
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 'lts/*' }}
        uses: actions/upload-artifact@v4.3.1
        with:
          name: extension
          path: extension.crx && extension.zip && extension.xpi
